language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t enxebre/kuwit .
  - docker run --name=kuwit -e WIT_TOKEN=FakeToken -p 8000:8000 enxebre/kuwit

script:
  - /bin/bash test.sh